### ISSUE TITLE
Geometry is not Serializable

### ISSUE THREAD

**Issue by negesti** [GeoLatte/geolatte-geom#34]
I hava a project using hibernate-spatial. With hibernate 5.0 the spatial project is a component in hibernate-orm and they use geolatte-geom. 
The Geometry object implements Serializable but can not be serialized when inside an hibernate Entity because not all properties can be serialized:

Using com.vividsolutions.jts.geom.Geometry (which was serializable) does not work either. Hibernate uses the PointSequenceCoordinateSequenceFactory which is not serializable.

**Comment by maesenka** [comment]
I started adding 'Serializable' every where but I realized it is not a good solution. I'm going to add full serialization using writeObject/readObject in the root Geometry class.

**Comment by negesti** [comment]
For the actual data processing (activemq) i just serialize the Coordinate which are Serializable "out of the box" but I had to add Serialize at serveral point to get the spring-batch HibernateCursorItemReader running and accecpting the (Oralce) SDO_GEOMETRY data.

A "real" write/readObject would be the nice and most likely the fastet.

**Comment by maesenka** [comment]
This should now be resolved by commit 93d1fedd0bea72d406a1c0a133586b3904b18c1c

**Comment by wafath** [comment]
I am still having this issue with the PointSequenceCoordinateSequenceFactory in Hibernate Spatial 5.2.1 and geolatte-geom 1.0.3.  Could the factories be made transient?

**Comment by maesenka** [comment]
This should now be resolved by commit 7918e43275c5fedbe6a2f8ec85447d4adab8984a.

This is released in version 1.0.5
